config/routes.rb
Deopt::Application.routes.draw do

  get "welcome/index"

  devise_for :users

controller :sessions do
  get "login"=>:new
  post "login"=>:create
end

  resources :users

  resources :people do 
 collection do
 get "new_people"
end
end

  resources :rooms  do
  collection  do
  get "kong_room"
end
  collection do
  get "old_people"
end
  collection do
  post "cao_zuo"
end
  collection do
  get  "chakan"
end
  collection do
  get   "edit_room"
end
  collection do
  get  "tuifang"
end
  collection do
  get "count"
end
end
 match  'rooms/download' => 'rooms#download'

   root :to => 'rooms#index'

end

app/models/person.rb
 # encoding:utf-8

class Person < ActiveRecord::Base
  attr_accessible  :address, :age, :name, :sex, :room, :time, :people_zhuangtai
  validates :name, :age, :address, :time, :sex, :presence => true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  @@current_person=[]
  @@current_room=[]
  # GET /people
  # GET /people.json
  def index
   @people=[]
    people = Person.all
    people.each do |people|
    @people<<people  if people.people_zhuangtai=="yi zhu"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    room=Room.find(params[:id])
    @@current_room<<room

    respond_to do |format|
      format.html
    end
  end
  def new_people
    @person = Person.new
     person = Person.find(params[:person_id])
    @@current_person<<person

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    r=[]
    @person = Person.new(params[:person])
    unless @@current_person.empty?
    person=@@current_person[0]
    @person.age=person.age
    @person.name=person.name
    @person.sex=person.sex
    @person.address=person.address
    @person.people_zhuangtai="yi zhu"
    @person.save
    end
    unless @@current_room.empty?
     @room=@@current_room[0]
     @person.room=@room.number
     @person.save
     
    end
    @person.people_zhuangtai="yi zhu"
    @person.save
    @room=Room.all
    @room.each do |room|
    room.num += 1  if room.number==@person.room 
    r<<room  if room.number==@person.room
    room.zhuangtai="yi kai" if room.number==@person.room
    room.update_attributes(params[:room])
    end

    respond_to do |format|
      if @person.save
        unless @@current_person.empty?
        @@current_person.delete_at(0)
        end
        unless @@current_room.empty?
        @@current_room.delete_at(0)
        end
        format.html { redirect_to chakan_rooms_path(:room_id=>r[0]), notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])
    room= Room.find(@person.room)
    room.num-=1
    room.zhuangtai="kong fang"  if room.num==0
    room.update_attributes(params[:room])
    @person.update_attributes(params[:person])
    @room= Room.find(@person.room)
      @room.zhuangtai="yi kai"  
      @room.num+=1  
    @room.update_attributes(params[:room])
    

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to chakan_rooms_path(:room_id=>@room), notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.people_zhuangtai="yi tui"
    @person.update_attributes(params[:person])
    
    @room=Room.find(@person.room)
    @room.num-=1 if @room.num>0
    @room.update_attributes(params[:room])
    
    respond_to do |format|
      if @room.num==0
    @room.zhuangtai="kong fang"    
    @room.update_attributes(params[:room])
      format.html { redirect_to rooms_url}
    else 
      format.html { redirect_to chakan_rooms_path(:room_id=>@room)}
      format.json { head :no_content }
    end
  end
end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
 <div id="form">
<%= simple_form_for @person   do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :name, label: '姓名', :class => "span5 off-set=6" %>
    <%= f.input :age, collection: 17..70, label:'年龄' %>
    <%= f.input :address, label:'地址' %>
    <%= f.input :time, collection: ["zhong dian","yi tian","liang tian"], label:'时间' %>
    <%= f.input :sex, collection: ["nan","nv"],label:'性别' %>
    <%= f.submit'确定', :class => ' btn btn-primary btn-inverse' %>
<% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :room%><br />
    <%= f.text_field :room%>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :time%><br />
    <%= f.text_field :time%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
   <div class ="row">
    <div class="span2">
      <h4>年龄<h4>
    </div>
    <div class="span2">
      <h4>房间<h4>
    </div>
    <div class="span2">
      <h4>姓名<h4>
    </div>
    <div class="span2">
      <h4>性别<h4>
    </div>
    <div class="span2">
      <h4>地址<h4>
    </div>
    <div class="span2">
      <h4>开房时间<h4>
    </div>
    <div class="span2">
      <h4>时间<h4>
    </div>
    <div class="span2">
      <h4>操作<h4>
    </div>
    </div>

<% @people.each do |person| %>
    <div class ="row">
    <div class ="span2">
    <%= person.age %>
    </div>
    <div class ="span2">
    <%= person.room%>
    </div>
    <div class ="span2">
    <%= person.name%>
    </div>
    <div class ="span2">
    <%= person.sex%>
    </div>
    <div class ="span2">
    <%= person.address%>
    </div>
    <div class ="span2">
    <%= person.created_at%>
    </div>
    <div class ="span2">
    <%= person.time%>
    </div>
    <div class ="span0">
    <%= link_to 'Edit', edit_person_path(person) %>
    </div>
    <div class ="span0">
    <%= link_to 'tui fang', person, :method=>:delete, data: { confirm: 'Are you sure?' } %>
    </div>
   </div>
  <%end%>

app/views/people/new.html.erb
<div id="form">
<%=render'form'%>
</div>

app/views/people/new_people.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :time%><br />
    <%= f.text_field :time%>
  </div>
  <div class="field">
    <%= f.label :room%><br />
    <%= f.text_field :room%>
  </div>
  <div class="field">
    <%= f.submit %><br />
  </div>
<%end%>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Age:</b>
  <%= @person.age %>
</p>

<p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>

<p>
  <b>Sex:</b>
  <%= @person.sex %>
</p>

<p>

  <b>Address:</b>
  <%= @person.address %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>
<%= button_to'que ding', rooms_path(:person_id=>@person) %>