config/routes.rb
Deopt::Application.routes.draw do

  get "welcome/index"

  devise_for :users

controller :sessions do
  get "login"=>:new
  post "login"=>:create
end

  resources :users

  resources :people do 
 collection do
 get "new_people"
end
end

  resources :rooms  do
  collection  do
  get "kong_room"
end
  collection do
  get "old_people"
end
  collection do
  post "cao_zuo"
end
  collection do
  get  "chakan"
end
  collection do
  get   "edit_room"
end
  collection do
  get  "tuifang"
end
  collection do
  get "count"
end
end
 match  'rooms/download' => 'rooms#download'

   root :to => 'rooms#index'

end

app/views/shared/_top.html.erb
 <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>
          </button>   
          <div class="collapse nav-collapse">  
            <ul class="nav navbar-nav">
              <li><%=link_to'home',rooms_url %></li>
              <li><%=link_to'已退客人',old_people_rooms_path%></li>
              <li><%=link_to'已住客人',people_path%></li>
              <li><%=link_to'添加房间',new_room_path%></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
             

<button type="button" class="btn btn-default navbar-btn">Sign in</button>


           
    </div>
         </div>
 