config/routes.rb
Deopt::Application.routes.draw do

  get "welcome/index"

  devise_for :users

controller :sessions do
  get "login"=>:new
  post "login"=>:create
end

  resources :users

  resources :people do 
 collection do
 get "new_people"
end
end

  resources :rooms  do
  collection  do
  get "kong_room"
end
  collection do
  get "old_people"
end
  collection do
  post "cao_zuo"
end
  collection do
  get  "chakan"
end
  collection do
  get   "edit_room"
end
  collection do
  get  "tuifang"
end
  collection do
  get "count"
end
end
 match  'rooms/download' => 'rooms#download'

   root :to => 'rooms#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible  :leibie, :number, :price, :zhuangtai, :people_number, :age, :sex, :name
  validates :leibie, :number, :price, :zhuangtai, :presence => true
  

       
def self.all_with_zhuangtai
     all.map do |room|
     {:id=>room.id, :zhuangtai=>room.zhuangtai}
    end
end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms=Room.all
    respond_to  do   |format|
     format.html
   end
  end
  # GET /rooms/1
  # GET /rooms/1.json
  def chakan
    @room=Room.find(params[:room_id])
    @p=[]
    @time=Time.now
    @person= Person.all
    @person.each do |person|
       if @room.number==person.room
          if person.people_zhuangtai=="yi zhu"
              @p<<person
           end
      end
    end
    respond_to do |format|
     if  @room.zhuangtai=="yi kai"
      format.html # show.html.erb
      format.xml {render :xml => @room.to_xml }# show.html.erb
      format.json { render json: @room }
     else
      format.html { redirect_to rooms_url }
    end
  end
end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html
   end
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to rooms_url, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room =Room.find(params[:id]) 
    @person= Person.all
    @person.each do |person|
    person.people_zhuangtai="yi tui"   if @room.number==person.room
    person.update_attributes(params[:person])
    end
    @room.zhuangtai="kong fang"
    @room.num=0
    @room.update_attributes(params[:room])

    respond_to do |format|
      
      format.html { redirect_to rooms_url}
      format.json { render json: @rooms }
  end
  end

  def old_people
    @people=[]
    persons=Person.all
    persons.each do |person|
    @people<<person if person.people_zhuangtai=="yi tui"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div id="form">
<%= simple_form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :leibie,collection:["tao fang","pu tong","dan jian"], label:'类别' %>
    <%= f.input :number,label:'编号' %>
    <%= f.input :price, label:'价格' %>
    <%= f.input :zhuangtai, collection:["yi kai","kong fang"], label:'状态' %>
    <%= f.submit'确定', :class => ' btn btn-primary btn-inverse' %>
<% end %>
</div>

app/views/rooms/chakan.html.erb
   <div class ="row">
    <div class="span2">
      <h4>年龄<h4>
    </div>
    <div class="span2">
      <h4>房间<h4>
    </div>
    <div class="span2">
      <h4>姓名<h4>
    </div>
    <div class="span2">
      <h4>性别<h4>
    </div>
    <div class="span2">
      <h4>地址<h4>
    </div>
    <div class="span2">
      <h4>开房时间<h4>
    </div>
    <div class="span2">
      <h4>时间<h4>
    </div>
    <div class="span2">
      <h4>操作<h4>
    </div>
    </div>

<% @p.each do |person| %>
    <div class ="row">
    <div class ="span2">
    <%= person.age %>
    </div>
    <div class ="span2">
    <%= person.room%>
    </div>
    <div class ="span2">
    <%= person.name%>
    </div>
    <div class ="span2">
    <%= person.sex%>
    </div>
    <div class ="span2">
    <%= person.address%>
    </div>
    <div class ="span2">
    <%= person.created_at%>
    </div>
    <div class ="span2">
    <%= person.time%>
    </div>
    <div class ="span0">
    <%= link_to 'Edit', edit_person_path(person) %>
    </div>
    <div class ="span0">
    <%= link_to 'tui fang', person, :method=>:delete, data: { confirm: 'Are you sure?' } %>
    </div>
   </div>
  <%end%>

<br />

Number:<%=@room.num%>
<%= link_to 'New Person', new_person_path(:id=>@room), :remote =>true %>

app/views/rooms/edit.html.erb
<div id="form">
<%=render'form'%>
</div>

app/views/rooms/index.html.erb
<div class="body">
 <table class="table-striped table table-bordered table-hover">
   <tr>
    <th><h4>类别<h4></th>
    <th><h4>编号<h4></th>
    <th><h4>状态<h4></th>
    <th><h4>价格<h4></th>
    <th></th>
   </tr>
<% @rooms.each do |room| %>
   <tr id='<%="room_#{room.id}"%>'>
    <td><%= room.leibie%></td>
     <td><%= room.number%></td>
    <td> <%= room.zhuangtai%></td>
     <td><%= room.price%></td>
    <td><%= link_to '查看', chakan_rooms_path(:room_id=>room)%>
   <%= link_to '开房', new_person_path(:id=>room) %>
    <%= link_to '退房',room, :method => :delete, :confirm =>'are you sure?'%></td>
    <td><%= link_to '编辑房间',edit_room_path(room)%></td>
   
  
</tr>
<% end %>
</table>
</div>

app/views/rooms/index.xml.erb
<p>bvluglg</p>

app/views/rooms/kai_fang.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%><br />
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :people_number %><br />
    <%= f.text_field :people_number%>
  </div>
  <div class="field">
    <%= f.label :age%><br />
    <%= f.text_field :age%>
  </div>
  <div class="field">
    <%= f.label :sex%><br />
    <%= f.text_field :sex%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%=link_to'back',kong_room_rooms_path%>

app/views/rooms/kong_room.html.erb
<h1>Kong rooms</h1>

<table>
  <tr>
    <th>Leibie</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Zhuangtai</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <td></td>
    <td></td>
    <th>Operation</th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.leibie %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= room.number %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= room.zhuangtai %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= room.price %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= link_to 'kai fang', new_person_path(:room_id=>room) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/rooms/new.html.erb
<div class ="row">
 </div>
<div class ="row">
 </div>
<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/old_people.html.erb
  <div class ="row">
    <div class="span2">
      <h4>年龄<h4>
    </div>
    <div class="span2">
      <h4>房间<h4>
    </div>
    <div class="span2">
      <h4>姓名<h4>
    </div>
    <div class="span2">
      <h4>性别<h4>
    </div>
    <div class="span2">
      <h4>地址<h4>
    </div>
    <div class="span2">
      <h4>开房时间<h4>
    </div>
    <div class="span2">
      <h4>时间<h4>
    </div>
    <div class="span2">
      <h4>操作<h4>
    </div>
    </div>

<% @people.each do |person| %>
    <div class ="row">
    <div class ="span2">
    <%= person.age %>
    </div>
    <div class ="span2">
    <%= person.room%>
    </div>
    <div class ="span2">
    <%= person.name%>
    </div>
     <div class ="span2">
    <%= person.sex%>
    </div>
    <div class ="span2">
    <%= person.address%>
    </div>
    <div class ="span2">
    <%= person.created_at%>
    </div>
    <div class ="span2">
    <%= person.time%>
    </div>
    <div class ="span0">
    <%=link_to'kai fang',new_people_people_path(:person_id=>person)%></td>
    </div>
   </div>
  <%end%>

app/views/rooms/show.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Age</th>
    <th></th>
    <th>Room</th>
    <th></th>
    <th>Name</th>
    <th></th>
    <th>Sex</th>
    <th></th>
    <th>Address</th>
    <th></th>
    <th>Kai Time</th>
    <th></th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @p.each do |person| %>
  <tr>
    <td><%= person.age %></td>
    <td></td>
    <td><%= person.room%></td>
    <td></td>
    <td><%= person.name %></td>
    <td></td>
    <td><%= person.sex %></td>
    <td></td>
    <td><%= person.address %></td>
    <td></td>
    <td><%= person.created_at%></td>
    <td></td>
    <td><%= person.time%></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'tui fang', person, :method=>:delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

Number:<%=$room[0].num%>
<%= link_to 'New Person', new_person_path(:room_id=>@room) %>